# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expectbest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField(verbose_name='Что мы делаем хорошо')),
                ('mission', models.TextField(verbose_name='Наша миссия')),
                ('value', models.TextField(verbose_name='Наша цель')),
            ],
            options={
                'verbose_name': 'Что мы лучше всего делаем',
            },
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Факты')),
            ],
            options={
                'verbose_name': 'Факты',
            },
        ),
        migrations.CreateModel(
            name='Lastwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Наши последние работы')),
                ('img', models.ImageField(upload_to='images', verbose_name='Наши последние работы Изображения')),
            ],
            options={
                'verbose_name': 'Последние работы',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='url')),
                ('banner', models.ImageField(blank=True, upload_to='images/banner', verbose_name='Баннер')),
                ('banner_info', models.TextField(verbose_name='Баннер Инфо')),
                ('body', models.TextField(default='Содержание', verbose_name='Содержание')),
                ('whoweare', models.BooleanField(default=False, verbose_name='Кто мы')),
                ('whatwedo', models.BooleanField(default=False, verbose_name='Что мы делаем')),
                ('fact', models.BooleanField(default=False, verbose_name='Факты')),
                ('lastwork', models.BooleanField(default=False, verbose_name='Последние работы')),
                ('portfolio', models.BooleanField(default=False, verbose_name='Портфолио')),
                ('expectbest', models.BooleanField(default=False, verbose_name='Делаем лучше')),
                ('team', models.BooleanField(default=False, verbose_name='Команда')),
                ('review', models.BooleanField(default=False, verbose_name='Отзывы')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/portfolio', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Портфолио',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Имя')),
                ('body', models.TextField(verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/team', verbose_name='Аватар')),
                ('name', models.CharField(max_length=300, verbose_name='Имя')),
                ('position', models.CharField(max_length=300, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Команда',
            },
        ),
        migrations.CreateModel(
            name='Whatwedo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Что мы делаем')),
            ],
            options={
                'verbose_name': 'Что мы делаем',
            },
        ),
        migrations.CreateModel(
            name='Whoweare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Кто мы')),
                ('whoweareimg', models.ImageField(upload_to='images', verbose_name='Кто мы изображение')),
            ],
            options={
                'verbose_name': 'Кто мы',
            },
        ),
    ]
