# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-09 09:23
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20170607_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('caption', models.CharField(max_length=1000, verbose_name='Захват')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Содержание')),
            ],
        ),
        migrations.RemoveField(
            model_name='page',
            name='banner_info',
        ),
        migrations.AlterField(
            model_name='expectbest',
            name='mission',
            field=ckeditor.fields.RichTextField(verbose_name='Наша миссия'),
        ),
        migrations.AlterField(
            model_name='expectbest',
            name='skills',
            field=ckeditor.fields.RichTextField(verbose_name='Что мы делаем хорошо'),
        ),
        migrations.AlterField(
            model_name='expectbest',
            name='value',
            field=ckeditor.fields.RichTextField(verbose_name='Наша цель'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Факты'),
        ),
        migrations.AlterField(
            model_name='lastwork',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Наши последние работы'),
        ),
        migrations.AlterField(
            model_name='page',
            name='banner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='page.Banner', verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='page',
            name='body',
            field=ckeditor.fields.RichTextField(default='Содержание', verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='whatwedo',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Что мы делаем'),
        ),
        migrations.AlterField(
            model_name='whoweare',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Кто мы'),
        ),
    ]
