# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-09 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20170609_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AddField(
            model_name='banner',
            name='img',
            field=models.ImageField(default=1, upload_to='media/banner', verbose_name='Изображение'),
        ),
    ]
