# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-09 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20170609_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(upload_to='media/banner', verbose_name='Изображение'),
        ),
    ]
