# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-09 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20170609_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='banner',
        ),
        migrations.AddField(
            model_name='page',
            name='banner',
            field=models.ManyToManyField(blank=True, to='page.Banner', verbose_name='Баннер'),
        ),
    ]
