# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-09 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_auto_20170609_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fact',
            name='body',
        ),
        migrations.AddField(
            model_name='fact',
            name='icon',
            field=models.CharField(default=1, max_length=300, verbose_name='Класс иконки'),
        ),
        migrations.AddField(
            model_name='fact',
            name='number',
            field=models.CharField(default=1, max_length=10, verbose_name='Цифра'),
        ),
        migrations.AddField(
            model_name='fact',
            name='title',
            field=models.CharField(default=1, max_length=500, verbose_name='Заголовок'),
        ),
        migrations.RemoveField(
            model_name='page',
            name='fact',
        ),
        migrations.AddField(
            model_name='page',
            name='fact',
            field=models.ManyToManyField(to='page.Fact', verbose_name='Факты'),
        ),
    ]
