# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-09 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_auto_20170609_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='icon',
            field=models.CharField(max_length=300, verbose_name='Класс иконки'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Цифра'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Заголовок'),
        ),
    ]
