# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-09 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_auto_20170609_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='link',
            field=models.URLField(default=1, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title',
            field=models.CharField(default=1, max_length=300, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(upload_to='images/banner', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='lastwork',
            name='img',
            field=models.ImageField(upload_to='images/last', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='whoweare',
            name='img',
            field=models.ImageField(upload_to='images/whoweare', verbose_name='Кто мы изображение'),
        ),
    ]
