# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-11 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0016_whatwedo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatwedo',
            name='link',
            field=models.CharField(max_length=200, verbose_name='Ссылка'),
        ),
    ]
