# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0017_auto_20170611_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='height',
            field=models.CharField(blank=True, max_length=30, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='position',
            field=models.CharField(default='social-marketing', max_length=200, verbose_name='Позиция'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='width',
            field=models.CharField(blank=True, max_length=30, verbose_name='Ширина'),
        ),
    ]
