# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0020_auto_20170612_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='blog',
            field=models.BooleanField(default=False, verbose_name='Блог'),
        ),
    ]
