# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 11:17
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0021_page_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Содержание'),
        ),
    ]
