# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0022_auto_20170612_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='fact',
            field=models.ManyToManyField(blank=True, to='page.Fact', verbose_name='Факты'),
        ),
        migrations.AlterField(
            model_name='page',
            name='lastwork',
            field=models.ManyToManyField(blank=True, to='page.Lastwork', verbose_name='Последние работы'),
        ),
        migrations.AlterField(
            model_name='page',
            name='whatwedo',
            field=models.ManyToManyField(blank=True, to='page.Whatwedo', verbose_name='Что мы делаем'),
        ),
    ]
