# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0027_page_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.TextField(default='Jgb', verbose_name='Описание'),
        ),
    ]
