# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0029_auto_20170612_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='pre_title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Title в заголовок'),
        ),
    ]
