# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 13:48
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0030_page_pre_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Содержание'),
        ),
    ]
