# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0031_auto_20170612_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='img',
            field=models.ImageField(default=1, upload_to='images/page', verbose_name='Изображение'),
        ),
    ]
