# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 14:30
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0035_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('body', ckeditor.fields.RichTextField(blank=True, verbose_name='Содержание')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Page', verbose_name='Страница к которой принадлежит')),
            ],
            options={
                'verbose_name': 'Секции',
                'verbose_name_plural': 'Секция',
            },
        ),
    ]
