# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0036_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.AddField(
            model_name='feedback',
            name='phone',
            field=models.CharField(default='12', max_length=12, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(verbose_name='Комментарий'),
        ),
    ]
