# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-11 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0037_auto_20171021_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=100, verbose_name='Заголовок сайта')),
                ('logo', models.ImageField(upload_to='page', verbose_name='Логотип')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('phone_mobile', models.CharField(blank=True, max_length=20, verbose_name='Мобильный телефон')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('footer_company_info', models.TextField(blank=True, verbose_name='Текст в подвале')),
            ],
            options={
                'verbose_name': 'Статические данные на сайте',
                'verbose_name_plural': 'Статические данные на сайте',
            },
        ),
    ]
