# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170612_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='born',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
