# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170628_0149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-born'], 'verbose_name': 'Блог статья', 'verbose_name_plural': 'Блог'},
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(default='23'),
        ),
    ]
