# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('img', models.ImageField(upload_to='images/portfolio', verbose_name='Изображение')),
                ('position', models.CharField(default='social-marketing', max_length=200, verbose_name='Позиция')),
                ('thumb', models.ImageField(upload_to='images/portfolio/thumb', verbose_name='Превью')),
                ('width', models.CharField(blank=True, max_length=30, verbose_name='Ширина')),
                ('height', models.CharField(blank=True, max_length=30, verbose_name='Высота')),
                ('link', models.URLField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name_plural': 'Портфолио',
                'verbose_name': 'Портфолио',
            },
        ),
    ]
