# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_portfolio_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='position',
            field=models.CharField(default='social', max_length=200, verbose_name='Позиция'),
        ),
    ]
