# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='client',
            field=models.CharField(blank=True, max_length=300, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='developer',
            field=models.CharField(blank=True, max_length=300, verbose_name='Разработчик'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='img2',
            field=models.ImageField(blank=True, upload_to='images/portfolio', verbose_name='Изображение2'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='img3',
            field=models.ImageField(blank=True, upload_to='images/portfolio', verbose_name='Изображение3'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='skills',
            field=models.CharField(blank=True, max_length=300, verbose_name='Скилы'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='year',
            field=models.IntegerField(default='2017', verbose_name='Год'),
        ),
    ]
