# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20170707_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(default='sdsd'),
        ),
    ]
