# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_portfolio_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='work',
            field=models.TextField(blank=True, verbose_name='Что было сдеано'),
        ),
    ]
