# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-06 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_portfolio_work'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-id'], 'verbose_name': 'Портфолио', 'verbose_name_plural': 'Портфолио'},
        ),
    ]
