# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('born', models.DateField(verbose_name='Дата')),
                ('name', models.CharField(max_length=300, verbose_name='Имя')),
                ('company', models.CharField(max_length=300, verbose_name='Компания')),
                ('prepayment', models.IntegerField(verbose_name='Предоплата')),
                ('budget', models.IntegerField(verbose_name='Бюджет')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Этап',
                'verbose_name_plural': 'Этапы',
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srm.Stage', verbose_name='Этап'),
        ),
    ]
