# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='prepayment',
            field=models.IntegerField(blank='True', verbose_name='Предоплата'),
        ),
    ]
