# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0002_auto_20170722_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='prepayment',
            field=models.IntegerField(blank=True, verbose_name='Предоплата'),
        ),
    ]
