# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0004_auto_20170722_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='prepayment',
            field=models.IntegerField(blank=True, null=True, verbose_name='Предоплата'),
        ),
    ]
