# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0005_auto_20170722_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='site',
            field=models.CharField(blank=True, max_length=250, verbose_name='Сайт'),
        ),
    ]
