# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 10:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0006_deal_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='prepayment_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Дата'),
        ),
    ]
