# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0007_deal_prepayment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='prepayment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата предоплаты'),
        ),
    ]
