# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 21:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0012_stage_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='born',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата'),
        ),
    ]
