# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-12 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0015_auto_20180312_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='name',
            field=models.ForeignKey(default='Full', on_delete=django.db.models.deletion.CASCADE, to='srm.Contact', verbose_name='Имя'),
        ),
    ]
