# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-12 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0017_auto_20180312_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='site',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
