# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-12 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0018_contact_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='site',
        ),
    ]
