# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-12 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0019_remove_deal_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srm.Contact', verbose_name='Имя'),
        ),
    ]
