# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-12 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0020_auto_20180312_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='name',
            new_name='contact',
        ),
    ]
