# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-12 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0021_auto_20180312_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='prepayment_date',
        ),
    ]
