# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0022_remove_deal_prepayment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindofWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['-born'], 'verbose_name': 'Сделка', 'verbose_name_plural': 'Сделки'},
        ),
        migrations.AddField(
            model_name='deal',
            name='kindofwork',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='srm.KindofWork'),
        ),
    ]
