# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-24 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0025_dealfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealfile',
            name='deal',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='srm.Deal'),
        ),
    ]
