# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-20 12:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0028_auto_20180409_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Статья расхода')),
                ('born', models.DateField(default=datetime.datetime.now, verbose_name='Когда')),
                ('price', models.IntegerField(verbose_name='Сумма')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srm.Deal', verbose_name='Сделка')),
            ],
            options={
                'verbose_name': 'Расходы',
                'verbose_name_plural': 'Расходы',
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['born'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
