# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0029_auto_20180520_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='В архив'),
        ),
    ]
